#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Workspace Runtime 策略模块。"""

from .browser_policy import (
    attach_browser_degrade_payload,
    build_browser_atomic_allowlist,
    build_browser_capability_gap_allowlist,
    build_browser_high_level_failure_key,
    build_browser_high_level_retry_block_message,
    build_browser_observation_fingerprint,
    build_browser_preferred_function_names,
    build_browser_route_block_message,
    build_browser_route_state_key,
    build_listing_click_target_block_message,
    coerce_optional_int,
    collect_temporarily_blocked_browser_high_level_function_names,
    extract_browser_tool_state,
    is_browser_high_level_temporarily_blocked,
    normalize_browser_page_type,
)
from .common import build_log_text_preview, compact_tool_value, hash_payload, truncate_tool_text
from .convergence_policy import (
    BLOCKED_TOOL_LOOP_BREAK_REASONS,
    build_human_wait_missing_interrupt_payload,
    build_loop_break_payload,
    build_recent_blocked_tool_call,
    build_recent_failed_action,
    build_search_fingerprint,
    build_tool_feedback_content,
    build_tool_fingerprint,
    normalize_execution_payload,
    summarize_tool_result_data,
)
from .task_mode_policy import (
    analyze_text_intent,
    build_step_candidate_text,
    build_task_mode_disallowed_names,
    classify_confirmed_user_task_mode,
    classify_file_access_intent,
    classify_step_task_mode,
    has_environment_write_intent,
    has_explicit_wait_semantics,
    is_allowed_in_task_mode,
    has_tool_execution_need,
    should_force_planner_for_tool_task,
)
from .step_contract_policy import (
    StepContractCompilationIssue,
    collect_step_contract_hard_issues,
    compile_step_contracts,
    filter_final_delivery_steps,
)

__all__ = [
    "analyze_text_intent",
    "attach_browser_degrade_payload",
    "BLOCKED_TOOL_LOOP_BREAK_REASONS",
    "build_browser_atomic_allowlist",
    "build_browser_capability_gap_allowlist",
    "build_browser_high_level_failure_key",
    "build_browser_high_level_retry_block_message",
    "build_browser_observation_fingerprint",
    "build_browser_preferred_function_names",
    "build_browser_route_block_message",
    "build_browser_route_state_key",
    "build_log_text_preview",
    "build_listing_click_target_block_message",
    "build_human_wait_missing_interrupt_payload",
    "build_loop_break_payload",
    "build_recent_blocked_tool_call",
    "build_recent_failed_action",
    "build_search_fingerprint",
    "build_step_candidate_text",
    "build_tool_feedback_content",
    "build_tool_fingerprint",
    "build_task_mode_disallowed_names",
    "classify_confirmed_user_task_mode",
    "classify_file_access_intent",
    "classify_step_task_mode",
    "has_environment_write_intent",
    "coerce_optional_int",
    "collect_temporarily_blocked_browser_high_level_function_names",
    "compact_tool_value",
    "extract_browser_tool_state",
    "has_explicit_wait_semantics",
    "has_tool_execution_need",
    "hash_payload",
    "is_allowed_in_task_mode",
    "is_browser_high_level_temporarily_blocked",
    "normalize_browser_page_type",
    "normalize_execution_payload",
    "should_force_planner_for_tool_task",
    "StepContractCompilationIssue",
    "collect_step_contract_hard_issues",
    "compile_step_contracts",
    "filter_final_delivery_steps",
    "summarize_tool_result_data",
    "truncate_tool_text",
]
