"""remove delivery_role delivery_content_state

Revision ID: 86bc17fa21eb
Revises: 3c4d5e6f7a8b
Create Date: 2026-04-24 10:16:24.026282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86bc17fa21eb'
down_revision: Union[str, Sequence[str], None] = '3c4d5e6f7a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_run_steps', 'delivery_context_state')
    op.drop_column('workflow_run_steps', 'delivery_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_run_steps', sa.Column('delivery_role', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('workflow_run_steps', sa.Column('delivery_context_state', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
