"""add long term memory table

Revision ID: 8b9d0cc0ff8a
Revises: e1f2a3b4c5d6
Create Date: 2026-03-30 17:02:08.531834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b9d0cc0ff8a'
down_revision: Union[str, Sequence[str], None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('long_term_memories',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('memory_type', sa.String(length=64), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('summary', sa.Text(), server_default=sa.text("''::text"), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('source', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_long_term_memories_id'),
    sa.UniqueConstraint('namespace', 'dedupe_key', name='uq_long_term_memories_namespace_dedupe_key')
    )
    op.create_index('ix_long_term_memories_memory_type', 'long_term_memories', ['memory_type'], unique=False)
    op.create_index('ix_long_term_memories_namespace', 'long_term_memories', ['namespace'], unique=False)
    op.create_index('ix_long_term_memories_updated_at', 'long_term_memories', ['updated_at'], unique=False)
    op.drop_index(op.f('ix_sessions_current_run_id'), table_name='sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sessions_current_run_id'), 'sessions', ['current_run_id'], unique=False)
    op.drop_index('ix_long_term_memories_updated_at', table_name='long_term_memories')
    op.drop_index('ix_long_term_memories_namespace', table_name='long_term_memories')
    op.drop_index('ix_long_term_memories_memory_type', table_name='long_term_memories')
    op.drop_table('long_term_memories')
    # ### end Alembic commands ###
