"""add summary table

Revision ID: cb806608ad1c
Revises: 8b9d0cc0ff8a
Create Date: 2026-04-01 09:28:13.632132

"""
from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb806608ad1c'
down_revision: Union[str, Sequence[str], None] = '8b9d0cc0ff8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_context_snapshots',
                    sa.Column('session_id', sa.String(length=255), nullable=False),
                    sa.Column('user_id', sa.String(length=255), nullable=True),
                    sa.Column('last_run_id', sa.String(length=255), nullable=True),
                    sa.Column('summary_text', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('recent_run_briefs', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'[]'::jsonb"), nullable=False),
                    sa.Column('open_questions', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'[]'::jsonb"), nullable=False),
                    sa.Column('artifact_refs', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'[]'::jsonb"), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('session_id', name='pk_session_context_snapshots_session_id')
                    )
    op.create_index('ix_session_context_snapshots_updated_at', 'session_context_snapshots', ['updated_at'],
                    unique=False)
    op.create_index('ix_session_context_snapshots_user_id', 'session_context_snapshots', ['user_id'], unique=False)
    op.create_table('workflow_run_summaries',
                    sa.Column('id', sa.String(length=255), nullable=False),
                    sa.Column('run_id', sa.String(length=255), nullable=False),
                    sa.Column('session_id', sa.String(length=255), nullable=False),
                    sa.Column('user_id', sa.String(length=255), nullable=True),
                    sa.Column('thread_id', sa.String(length=255), nullable=True),
                    sa.Column('goal', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('title', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('final_answer_summary', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('final_answer_text', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('status', sa.String(length=64), server_default=sa.text("'completed'::character varying"),
                              nullable=False),
                    sa.Column('completed_steps', sa.Integer(), server_default=sa.text('0'), nullable=False),
                    sa.Column('total_steps', sa.Integer(), server_default=sa.text('0'), nullable=False),
                    sa.Column('step_ledger', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'[]'::jsonb"), nullable=False),
                    sa.Column('artifacts', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'[]'::jsonb"), nullable=False),
                    sa.Column('open_questions', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'[]'::jsonb"), nullable=False),
                    sa.Column('blockers', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'[]'::jsonb"), nullable=False),
                    sa.Column('facts_learned', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'[]'::jsonb"), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name='pk_workflow_run_summaries_id'),
                    sa.UniqueConstraint('run_id', name='uq_workflow_run_summaries_run_id')
                    )
    op.create_index('ix_workflow_run_summaries_created_at', 'workflow_run_summaries', ['created_at'], unique=False)
    op.create_index('ix_workflow_run_summaries_session_id', 'workflow_run_summaries', ['session_id'], unique=False)
    op.create_index('ix_workflow_run_summaries_user_id', 'workflow_run_summaries', ['user_id'], unique=False)
    op.add_column('long_term_memories',
                  sa.Column('content_text', sa.Text(), server_default=sa.text("''::text"), nullable=False))
    op.add_column('long_term_memories', sa.Column('search_tsv', postgresql.TSVECTOR(), nullable=True))
    op.add_column('long_term_memories',
                  sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.create_index('ix_long_term_memories_search_tsv', 'long_term_memories', ['search_tsv'], unique=False,
                    postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_long_term_memories_search_tsv', table_name='long_term_memories', postgresql_using='gin')
    op.drop_column('long_term_memories', 'embedding')
    op.drop_column('long_term_memories', 'search_tsv')
    op.drop_column('long_term_memories', 'content_text')

    op.drop_index('ix_workflow_run_summaries_user_id', table_name='workflow_run_summaries')
    op.drop_index('ix_workflow_run_summaries_session_id', table_name='workflow_run_summaries')
    op.drop_index('ix_workflow_run_summaries_created_at', table_name='workflow_run_summaries')
    op.drop_table('workflow_run_summaries')
    op.drop_index('ix_session_context_snapshots_user_id', table_name='session_context_snapshots')
    op.drop_index('ix_session_context_snapshots_updated_at', table_name='session_context_snapshots')
    op.drop_table('session_context_snapshots')
    # ### end Alembic commands ###
