"""

Revision ID: d7cfc3374fa2
Revises: 0f1e2d3c4b5a
Create Date: 2026-04-29 18:29:04.038233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7cfc3374fa2'
down_revision: Union[str, Sequence[str], None] = '0f1e2d3c4b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_long_term_memories_namespace_dedupe_key'), 'long_term_memories', type_='unique')
    op.create_unique_constraint('uq_long_term_memories_user_namespace_dedupe_key', 'long_term_memories', ['user_id', 'namespace', 'dedupe_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_long_term_memories_user_namespace_dedupe_key', 'long_term_memories', type_='unique')
    op.create_unique_constraint(op.f('uq_long_term_memories_namespace_dedupe_key'), 'long_term_memories', ['namespace', 'dedupe_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
