#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Feedback Ledger 领域模型 re-export。

反馈领域契约统一定义在 runtime contract 中，避免 domain/models 与
持久化模型维护第二套不一致的 Pydantic 结构。
"""

from app.domain.services.runtime.contracts.feedback_contract import (
    ExcludedFeedbackRefResult,
    FeedbackCategory,
    FeedbackClassificationResult,
    FeedbackDataOrigin,
    FeedbackEventPayloadResult,
    FeedbackExcludedBy,
    FeedbackGapKind,
    FeedbackGapResult,
    FeedbackInputEventPayloadResult,
    FeedbackKind,
    FeedbackPromptSafeSummaryResult,
    FeedbackReasonCode,
    FeedbackRecord,
    FeedbackRecordCommand,
    FeedbackRecordResult,
    FeedbackResolutionCommand,
    FeedbackResolutionReasonCode,
    FeedbackResolutionResult,
    FeedbackScopeKind,
    FeedbackScopeResult,
    FeedbackSeverity,
    FeedbackSnapshotCursorResult,
    FeedbackSnapshotItemResult,
    FeedbackSnapshotResult,
    FeedbackSnapshotScopeResult,
    FeedbackSnapshotStage,
    FeedbackSourceConfidence,
    FeedbackSourceKind,
    FeedbackSourceRefResult,
    FeedbackStatus,
    FeedbackSummaryKind,
    FeedbackSummaryResult,
    FeedbackTargetRefResult,
    FeedbackTargetType,
    FeedbackWriteResult,
    QualityFeedbackCommand,
    RuntimeFeedbackCommand,
    UserFeedbackCaptureResult,
    UserFeedbackCommand,
    UserFeedbackIntent,
    UserFeedbackIntentKind,
    build_feedback_record_from_result,
    build_feedback_record_result,
    map_feedback_data_origin_to_data_origin,
)
from app.domain.services.runtime.contracts.feedback_runtime_ports import (
    FeedbackRecorderPort,
    FeedbackSnapshotProviderPort,
)

__all__ = [
    "ExcludedFeedbackRefResult",
    "FeedbackCategory",
    "FeedbackClassificationResult",
    "FeedbackDataOrigin",
    "FeedbackEventPayloadResult",
    "FeedbackExcludedBy",
    "FeedbackGapKind",
    "FeedbackGapResult",
    "FeedbackInputEventPayloadResult",
    "FeedbackKind",
    "FeedbackPromptSafeSummaryResult",
    "FeedbackRecorderPort",
    "FeedbackReasonCode",
    "FeedbackRecord",
    "FeedbackRecordCommand",
    "FeedbackRecordResult",
    "FeedbackResolutionCommand",
    "FeedbackResolutionReasonCode",
    "FeedbackResolutionResult",
    "FeedbackScopeKind",
    "FeedbackScopeResult",
    "FeedbackSeverity",
    "FeedbackSnapshotCursorResult",
    "FeedbackSnapshotItemResult",
    "FeedbackSnapshotResult",
    "FeedbackSnapshotScopeResult",
    "FeedbackSnapshotStage",
    "FeedbackSnapshotProviderPort",
    "FeedbackSourceConfidence",
    "FeedbackSourceKind",
    "FeedbackSourceRefResult",
    "FeedbackStatus",
    "FeedbackSummaryKind",
    "FeedbackSummaryResult",
    "FeedbackTargetRefResult",
    "FeedbackTargetType",
    "FeedbackWriteResult",
    "QualityFeedbackCommand",
    "RuntimeFeedbackCommand",
    "UserFeedbackCaptureResult",
    "UserFeedbackCommand",
    "UserFeedbackIntent",
    "UserFeedbackIntentKind",
    "build_feedback_record_from_result",
    "build_feedback_record_result",
    "map_feedback_data_origin_to_data_origin",
]
